# Generated by Django 3.1 on 2021-03-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='problem',
            new_name='post',
        ),
    ]
