# Generated by Django 3.1 on 2021-03-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210315_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='likes_unlikes',
            new_name='likes',
        ),
    ]
